# This script is used to run MIPS assembly code generated by the compiler, using the MARS simulator.

# Usage: ./mips_run.sh <file.s>

# Check if the number of arguments is correct
if [ "$#" -ne 1 ]; then
    echo "Usage: ./mips_run.sh <file.s>"
    exit 1
fi

asm_file=$1

# Check if the file exists
if [ ! -f $asm_file ]; then
    echo "File $asm_file not found!"
    exit 1
fi

# Check required tools
if ! command -v java &>/dev/null; then
    echo "Command java not found! Please install Java."
    exit 1
fi

# Check if MARS_PATH is set
if [ -z "$MARS_PATH" ]; then
    echo "MARS_PATH is not set! Please set it to the MARS simulator path."
    exit 1
fi

# Check if MARS simulator exists
if [ ! -f "$MARS_PATH" ]; then
    echo "MARS simulator not found in $MARS_PATH! Please set MARS_PATH to the MARS simulator path."
    exit 1
fi

# Run the MARS simulator with the assembly file
java -jar "$MARS_PATH" nc $asm_file
