#pragma once

#include <string>

/**
 * @brief `Token` is a class that represents a token generated by the lexer. And it
 * is consumed by the parser.
 */
struct Token {
    enum TokenType {
        TK_IDENT,
        TK_NUMBER,
        TK_FN,
        TK_LPARENT,
        TK_RPARENT,
        TK_RARROW,
        TK_SEMINCN,
        TK_VAR,
        TK_GET,
        TK_PUT,
        TK_TAG,
        TK_LET,
        TK_ASSIGN,
        TK_IF,
        TK_TO,
        TK_PLUS,
        TK_MINU,
        TK_MULT,
        TK_DIV,
        TK_MOD,
        TK_LT,
        TK_GT,
        TK_LE,
        TK_GE,
        TK_EQ,
        TK_NE,
        TK_COMMA,
        TK_ERR, // error token, used if the lexer encounters an invalid character
        TK_EOF, // end of file token, used to indicate the end of the input
    } type;
    std::string content;
    int lineno;

    Token() = default;

    Token(TokenType type, std::string content, int lineno)
        : type(type), content(content), lineno(lineno) {}
};
