name: Pull Request Check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [ "ubuntu-22.04", "macos-14" ]
        backend: [ "llvm", "pcode" ]

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v4

    - name: Build
      env:
        BUILD_TYPE: ${{env.BUILD_TYPE}}
      run: bash ./scripts/build.sh ${{matrix.backend}}

    - name: Unit test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

  test:
    needs: build

    strategy:
      matrix:
        os: [ "ubuntu-22.04", "macos-14" ]
        stage: [ "llvm", "pcode", "mips" ]

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v4

    - name: Install llvm
      if: matrix.stage == 'llvm'
      uses: KyleMayes/install-llvm-action@v2
      with:
        version: "16.0"

    - name: Install MARS for mips
      if: matrix.stage == 'mips'
      run: wget https://courses.missouristate.edu/KenVollmar/MARS/MARS_4_5_Aug2014/Mars4_5.jar -O ${{github.workspace}}/mars.jar

    - name: Run test script
      run: python ./scripts/test.py -s ${{matrix.stage}} -d ${{github.workspace}}/testcases
